version: 1.0.{build}

environment:
  CYG_BASH: C:\cygwin\bin\bash

clone_depth: 1

install:
  - '%CYG_BASH% -lc "perl -V"'
  - '%CYG_BASH% -lc "lwp-download https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm C:/projects/cpanm"'
  - '%CYG_BASH% -lc "cpanm -q --with-develop --with-suggests --installdeps ."'
  
build_script:
  - '%CYG_BASH% -lc "perl Makefile.PL"'

test_script:
  - '%CYG_BASH% -lc "make test"'
  - '%CYG_BASH% -lc "prove -bv xt/*.t"'
