version: 1.0.{build}

clone_depth: 1

os:
  - MinGW


install:
  # running under CI
  - set CI_TESTING=1
  - perl -V
  - dir
  - PATH
  - gcc --version
  - make --help
  - dmake --help
  - cpan App::cpanminus
  - cpanm -q --with-develop --with-suggests --installdeps .
  - 'echo End install at: & time /t'

build_script:
  - perl Makefile.PL

test_script:
  - dmake test
