version: 1.0.{build}

environment:
  CYG_BASH: C:\cygwin\bin\bash

clone_depth: 1

install:
  - '%CYG_BASH% -lc "perl -V"'
  
build_script:
  - '%CYG_BASH% -lc "perl Makefile.PL"'

test_script:
  - '%CYG_BASH% -lc "make test"'
  - '%CYG_BASH% -lc "prove -bv xt/*.t"'
