version: 1.0.{build}

clone_depth: 1

install:
  # running under CI
  - set CI_TESTING=1
  - perl -V
  - PATH
  - ppm install dmake
  - mkdir C:\Perl\cpan\build
  - lwp-download https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm cpanm
  - cpanm .
  - 'echo End install at: & time /t'

build_script:
  - perl Makefile.PL

test_script:
  - dmake test
