version: 1.0.{build}

install:
  # running under CI
  - set CI_TESTING=1
  - perl -V
  - cpan App::cpanminus
  - cpanm -q --with-develop --with-suggests .
  - 'echo End install at: & time /t'

build_script:
  - perl Makefile.PL

test_script:
  - dmake test
