version: 1.0.{build}

clone_depth: 1

configuration:
  - ActivePerl
  - Strawberry
  
install:
- ps: >-
  If (${env:CONFIGURATION} -eq "ActivePerl") {
    path C:\MinGW;C:\MinGW\bin;C:\MinGW\msys\1.0;%PATH%
    ppm install dmake Test::Pod
    lwp-download https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm C:/projects/cpanm
  } else {
    cinst StrawberryPerl
    path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  }
  perl -V
- perl C:/projects/cpanm -q --with-develop --with-suggests --installdeps .
  
build_script:
  - perl Makefile.PL

test_script:
  - dmake test
  - prove -bv xt/*.t
