version: 1.0.{build}

clone_depth: 1

install:
  - cinst StrawberryPerl
  - perl -V
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cpanm -q --with-develop --with-suggests --installdeps .
  
build_script:
  - perl Makefile.PL

test_script:
  - dmake test
