version: 1.0.{build}

install:
  # running under CI
  - set CI_TESTING=1
  - perl -V
  - cpan App::cpanminus
  - cpanm -q --showdeps --with-develop --with-suggests . | findstr /v "^perl\>" | cpanm -n
  - 'echo End intall at: & time /t'

build_script:
  - perl Makefile.PL

test_script:
  - dmake test
