version: 1.0.{build}

environment:
  CYG_BASH: C:\cygwin\bin\bash

clone_depth: 1

install:
  - set "PATH=C:\cygwin\usr\local\bin;C:\cygwin\bin;%PATH%"
  - curl -fSL -o C:/projects/cpanm https://raw.githubusercontent.com/miyagawa/cpanminus/master/cpanm
  - perl C:/projects/cpanm --with-develop --with-suggests --installdeps .
  - perl -V
  
build_script:
  - perl Makefile.PL

test_script:
  - make test
  - prove -bv xt/*.t
